// Generated by CoffeeScript 1.4.0
var Ball;

Ball = (function() {

  Ball.prototype.x = 0;

  Ball.prototype.y = 0;

  Ball.prototype.level = 0;

  Ball.prototype.game = null;

  Ball.prototype.radius = 0;

  Ball.prototype.tworPI = 2 * Math.PI;

  Ball.prototype.active = false;

  function Ball(level, game) {
    this.level = level;
    this.game = game;
    _.bindAll(this);
    $(this.game.canvas).bind('mousemove', this.moveBall);
    $(this.game.canvas).bind('touchmove', this.moveBall);
  }

  Ball.prototype.moveBall = function(event) {
    this.x = event.offsetX - this.radius / 2;
    this.y = event.offsetY - this.radius / 2;
    this.radius += 1;
    return this.draw();
  };

  Ball.prototype.stop = function() {
    $(this.game.canvas).unbind('mousemove', this.moveBall);
    return $(this.game.canvas).unbind('touchmove', this.moveBall);
  };

  Ball.prototype.update = function(dt) {};

  Ball.prototype.draw = function() {
    this.game.context.beginPath();
    this.game.context.stroke();
    this.game.context.fillStyle = '#FFFFFF';
    this.game.context.beginPath();
    this.game.context.arc(this.x, this.y, this.radius, 0, this.tworPI);
    this.game.context.fill();
    return this.game.context.fillStyle = '#ffffff00';
  };

  return Ball;

})();
